[package]
name = "ale"
version = "0.0.1"
authors = ["Callum Tolley <cgtrolley@gmail.com>"]
edition = "2018"
description = "A Rust encapsulation of the Arcade Learning Environment"

[workspace]
members = ["ale-sys"]

[dependencies]
ale-sys = { path = "ale-sys" }
