[package]
name = "ale-sys"
version = "0.1.0"
authors = ["Callum Tolley <cgtrolley@gmail.com>"]
edition = "2018"
description = "Rust bindings to the Arcade Learning Environment"
build = "build.rs"

[dependencies]
#libc = "*" # TODO

[build-dependencies]
#cmake = "*" # TODO
