on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

name: CI

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: List files
        run: ls -l /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.8.xctoolchain/usr/lib/c++/v1
